theme: jekyll-theme-architect
title: ChorusText Home
description: ChorusText is an open assistive device built with Arduino and Linux Single-Board-Computer. It turns text-editing from a visually oriented task into a tactile + audial task
